nmea_socket_driver fixes for ROS2
ros-drivers/nmea_navsat_driver pull request #127
Opened 2021-05-18 22:03 UTC by bsirang

I made these updates to get nmea_socket_driver node functioning in my ROS2 foxy environment.

2021-05-18 22:04 UTC, bsirang commented
@evenator please take a look

2021-05-23 02:06 UTC, evenator requested changes
Thanks for this contribution. As you may have guessed, the ROS 2 package is on the back burner and depends on the support of community developers like you. I have 1 small request--other than that, I just have to do a final test, and then I think this should be good to merge.

2021-05-23 02:06 UTC, evenator commented on src/libnmea_navsat_driver/nodes/nmea_socket_driver.py
> +                data_list = data.decode("utf-8").strip().split("\n")
I think this should use `ascii` encoding, since NMEA standard specifies ASCII. That would also match the ROS1 version of this driver.

2021-05-23 18:00 UTC, bsirang commented on src/libnmea_navsat_driver/nodes/nmea_socket_driver.py
> +                data_list = data.decode("utf-8").strip().split("\n")
I think this would be fine as is since `utf-8` is compatible with ascii, but makes sense to match the ROS1 version. I'll push the change now.

2021-06-04 21:45 UTC, evenator approved these changes

2021-06-04 21:46 UTC, merged

2021-06-04 21:47 UTC, evenator commented
Thank you for your contribution!