Add Support for TCP GNSS Sensor
ros-drivers/nmea_navsat_driver pull request #152
Opened 2022-07-15 19:30 UTC by BerndSchmecka

I added a new `nmea_tcpclient_driver`, because Sensors like the `Emlid Reach RS2` do not offer any UDP connection, but transmit NMEA-Sentences on Port 9001/tcp. The `nmea_tcpclient_driver` connects to it via TCP and forwards the NMEA-Sentences line by line to the driver.

*PS: Sorry about the commit-Messages, got a little exhausted during debugging ;)*

2022-07-16 20:02 UTC, evenator commented
Thanks for the contribution. I'll review the PR soon!

2022-11-15 18:22 UTC, evenator requested changes
I have some requests and suggestions. Thanks for the PR!

2022-11-15 18:22 UTC, evenator commented on launch/nmea_socket_driver.launch.py
> +# Copyright 2018 Open Source Robotics Foundation, Inc.
Please update this to 2022.

2022-11-15 18:22 UTC, evenator commented on launch/nmea_tcpclient_driver.launch.py
> +# Copyright 2018 Open Source Robotics Foundation, Inc.
Please update this to 2022.

2022-11-15 18:22 UTC, evenator commented on src/libnmea_navsat_driver/nodes/nmea_tcpclient_driver.py
> +# This is for you, Köter :P
To avoid licensing conflicts, please put the same OSRF Apache license on this file..

2022-11-15 18:22 UTC, evenator commented on src/libnmea_navsat_driver/nodes/nmea_tcpclient_driver.py
> +import socket;
Please remove the unnecessary semicolons.

2022-11-15 18:22 UTC, evenator commented on src/libnmea_navsat_driver/nodes/nmea_tcpclient_driver.py
> +                full_lines, last_line = lines[:-1], lines[-1]
Try this:

```python
lines = partial.splitlines()
if partial.endswith('\n'):
    full_lines = lines
    partial = ""
else:
    full_lines = lines[:-1]
    partial = lines[-1]
```

Then you can remove lines 53 and 54 (stripping line endings) and all of the logic on lines 64-79.

2022-11-15 18:24 UTC, evenator commented
Also, I'm sorry it took so long for me to review this. Maintaining this package is a side hobby for me, and it often gets away from me.

2022-11-15 19:37 UTC, BerndSchmecka commented on src/libnmea_navsat_driver/nodes/nmea_tcpclient_driver.py
> +                full_lines, last_line = lines[:-1], lines[-1]
Thank you for this suggestion :D

2022-11-15 19:39 UTC, BerndSchmecka commented
>  I'm sorry it took so long for me to review this. Maintaining this package is a side hobby for me, and it often gets away from me.

No problem, I appreciate that you use your free time for maintaining this. It has been really useful for me during a project for university.

> I have some requests and suggestions. Thanks for the PR!

I now implemented those changes.

2022-11-16 00:32 UTC, evenator requested changes
One small nit to fix. Other than that, I think this looks pretty good.

2022-11-16 00:32 UTC, evenator commented on launch/nmea_serial_driver.launch.py
> -# Copyright 2018 Open Source Robotics Foundation, Inc.
Can you remove this unrelated change?

2022-11-17 11:49 UTC, BerndSchmecka commented
Reverted the change

2022-11-21 00:53 UTC, evenator approved these changes
Looks good to me. Thanks for contributing this.

2022-11-21 00:54 UTC, merged